### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by xieqi**

### CODE REVIEW

**Review by jikunshang — APPROVED** [review]
LGTM. But would it be better if we put useful code into a new branch?  cc @winningsix

**Comment by winningsix** [comment]
Looks good. Let's create a new branch.

**Comment by xieqi** [comment]
Created a new branch p-cleanup for useful code. @jikunshang @winningsix

**Comment by winningsix** [comment]
@xieqi  We need to alert team for the migration.

**Pull request merged**
